server:
  port: 80

spring:
  application:
    name: ui
  cloud:
      config:
        enabled: true
        discovery:
          enabled: true
          service-id: config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true